name: spif
# conda environment for SPIF repository

dependencies:
  - python>=3.6
  - Cython
  - h5py
  - hdf5
  - ipython
  - natsort
  - nose
  - numpy
  - matplotlib
  - opencv
  - pandas
  - pep8
  - pytest
  - pytz
  - pyyaml
  - netCDF4
  - scipy>=1.1
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib>=1.0
  - sphinxcontrib-websupport>=1.1
  - xarray>=0.11
  - yaml
